DROP TABLE IF EXISTS SYMBOLS;

CREATE TABLE SYMBOLS  (
	ID BIGINT  NOT NULL PRIMARY KEY AUTO_INCREMENT,
	SYMBOL VARCHAR(5) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	INGESTED BOOL NULL
) ENGINE=InnoDB;

DROP TABLE IF EXISTS QUOTES;

CREATE TABLE QUOTES  (
	ID BIGINT  NOT NULL PRIMARY KEY AUTO_INCREMENT,
	SYMBOL VARCHAR(5) NOT NULL,
	TIME DATE NOT NULL,
	HIGH DECIMAL(12,4) NULL,
	LOW DECIMAL(12,4) NULL,
	OPEN DECIMAL(12,4) NULL,
	CLOSE DECIMAL(12,4) NULL,
	VOLUME BIGINT NULL
) ENGINE=InnoDB;
