DROP TABLE IF EXISTS SYMBOLS;

CREATE TABLE SYMBOLS  (
	ID BIGINT  NOT NULL PRIMARY KEY SERIAL,
	SYMBOL VARCHAR(5) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	INGESTED BOOL NULL
);

DROP TABLE IF EXISTS QUOTES;

CREATE TABLE QUOTES  (
	ID BIGINT  NOT NULL PRIMARY KEY SERIAL,
	SYMBOL VARCHAR(5) NOT NULL,
	TIME DATE NOT NULL,
	HIGH DECIMAL(12,2) NULL,
	LOW DECIMAL(12,2) NULL,
	OPEN DECIMAL(12,2) NULL,
	CLOSE DECIMAL(12,2) NULL,
	VOLUME BIGINT NULL
);
